version: '3.8'

services:
  web:
    container_name: app_container
    build: 
      context: ./app
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    container_name: pg_container
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./.env.pgadmin4
    ports:
      - 5050:80
    depends_on:
      - db


# To persist the data beyond the life of the container we configured a volume. 
# This config will bind postgres_data to the "/var/lib/postgresql/data/" directory in the container.

volumes:
  postgres_data:      